name: "Put milestones on autopilot"
on:
  schedule:
  - cron: "0 * * * *"

jobs:
  milestones:
    runs-on: ubuntu-latest
    steps:
    - uses: instantish/memorable-milestones@v1.1.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
